services:
  app:
    container_name: cinema-app
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        AUTORUN_ENABLED: true
        AUTORUN_DEBUG: true
        AUTORUN_LARAVEL_MIGRATION_SEED: true
    environment:
      PHP_DATE_TIMEZONE: "Europe/Warsaw"
      PHP_OPCACHE_ENABLE: "1"
    ports:
      - "81:8080"
    labels:
      - traefik.enable=true
      - traefik.http.routers.cinema.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.http.routers.cinema.entrypoints=web
      - traefik.http.services.cinema.loadbalancer.server.port=81
    networks:
      - cinema
      - traefik
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started

  database:
    container_name: cinema-database
    image: postgres:18.1-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME:-cinema}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_DATABASE:-cinema}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cinema

  redis:
    container_name: cinema-redis
    image: redis:8.0.2-alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-password}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - cinema

volumes:
  postgres_data:
  redis_data:

networks:
  cinema:
    driver: bridge
  traefik:
    external: true
